### ISSUE TITLE
  Call to undefined method MHasnainJafri\Cpanel\CpanelFacade::callUAPI()

### ISSUE THREAD

**Issue by milhami** [MHasnainJafri/cpanel#1]
I got these error

`php8.1 artisan app:get-certificate
MHasnainJafri\Cpanel\CpanelFacade Object
(
)

   Error 

  Call to undefined method MHasnainJafri\Cpanel\CpanelFacade::callUAPI()

  at app/Console/Commands/GetCertificate.php:37
     33▕         $Module="SSL";
     34▕         $function="fetch_best_for_domain";
     35▕         $parameters_array=["*.example.com"];
     36▕         print_r ($cpanel);
  ➜  37▕         $hasil = $cpanel->callUAPI($Module, $function, $parameters_array = array());
     38▕         print_r($hasil);
     39▕     }
     40▕ }
     41▕ 

      +12 vendor frames 

  13  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()`

**Comment by MHasnainJafri** [comment]
Thank you for reaching out and sharing the error you encountered. could you please provide additional details such as:

The version of PHP you're using (e.g., PHP 8.1).
The framework you're working with (if applicable).
Also the code you write giving you this error

**Comment by MHasnainJafri** [comment]
import will be 
use MHasnainJafri\Cpanel\Cpanel;

it should be called like this

$cpanel = new Cpanel();
$domain = ["domain" => "example.com"]; 
$response = $cpanel->callUAPI("SSL", "fetch_best_for_domain",$domain );
print_r($response);



Usage Of this function
This function retrieves the best-available certificate for the domain. The function also retrieves the certificate's associated private key and CA bundle, if available.

**Comment by milhami** [comment]
Thank you. The code run perfectly now.
